### ISSUE TITLE
请添加 g.co 

### ISSUE THREAD

**Issue by solitudechn** [clowwindy/gfwlist2pac#27]
第一次用，刚才点错了，抱歉 g.co 是好多google的短域名跳转

**Comment by clowwindy** [comment]
就算你不知道这只是个转换器，增加条目该反馈给 GFWList：
https://github.com/clowwindy/gfwlist2pac/pull/18

也已经在 PAC 里了：
https://github.com/clowwindy/gfwlist2pac/blob/master/test/proxy.pac#L1457
