### ISSUE TITLE
pcmag has just been found blocked

### ISSUE THREAD

**Issue by PieJesu** [clowwindy/gfwlist2pac#29]
Please add the line below to next version proxy list.
"www.pcmag.com",

**Comment by ericyan** [comment]
Please report your findings to the [GFWList](https://code.google.com/p/autoproxy-gfwlist/) project.

`gfwlist2pac` itself does not maintain a list of blocked domains; it just generates PAC file from GFWList.

**Comment by tinymins** [comment]
I find that https://code.google.com/p/autoproxy-gfwlist/issues/entry always return 400 error and I cannot report to GFWList

**Comment by lenovo-me** [comment]
@tinymins 400问题clowwindy已经帮你们反馈了，等Google回复吧...
https://code.google.com/p/support/issues/detail?id=33910
