### ISSUE TITLE
使用shadowsocks客户端从gfwlist更新的pac名单里竟然没有google.com

### ISSUE THREAD

**Issue by thundercn** [clowwindy/gfwlist2pac#32]
如题，更新pac后在pac模式下无法打开google.com，但是youtube可以，查来查去发现原来pac文件里竟然没有google.com。手动添加之后就可以访问google了。不知这个问题出现在哪里，期待解决。
客户端是这个：http://sourceforge.net/projects/shadowsocksgui/files/dist/

**Comment by clowwindy** [comment]
https://github.com/clowwindy/gfwlist2pac/issues/29
