### ISSUE TITLE
parse_gfwlist与get_hostname处理特殊规则时出现错误

### ISSUE THREAD

**Issue by BlackGear** [clowwindy/gfwlist2pac#42]
gfw2pac在处理gfwlist中的如下两行时出现了错误
hk*.nextmedia.com
tw*.nextmedia.com

测试代码如下：
line = ['hk*.nextmedia.com']
print(parse_gfwlist(line))
print(get_hostname('hk/.nextmedia.com'))

返回结果：
set(['hk'])
hk

这一问题导致gfwlist产生的pac文件中有： "tw": 1,  "hk": 1, 这两条错误的规则。

**Comment by clowwindy** [comment]
规则暂时不想调整，如果要精确匹配可以用 precise 模式代替。
